import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
  variable: "--font-poppins"
})

export const metadata: Metadata = {
  title: "Gestion de stock",
  description: "Generated by team ninjaCode",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(poppins.variable, 'font-poppins bg-[#ecedf8]')}
      >
        {children}
      </body>
    </html>
  );
}
